Introducing SRGF v1.0
UIGF-org/UIGF-org.github.io pull request #16
Opened 2023-05-21 11:09 UTC by Lightczx

2023-05-21 11:17 UTC, TremblingMoeNew requested changes
`gacha_type` should be 1, 2, 11 or 12

2023-05-21 11:22 UTC, TremblingMoeNew approved these changes

2023-05-21 11:23 UTC, Lightczx commented
Let's wait @Masterain98

2023-05-21 16:35 UTC, DancingSnow0517 commented on docs/zh/standards/SRGF.md
> +        },
`region_time_zone` 好像是一个 int 吧，原始api给的是数字

2023-05-22 02:23 UTC, Masterain98 approved these changes
- Added the English version
- Added language format

2023-05-22 02:23 UTC, merged

2023-05-22 02:24 UTC, Masterain98 commented on docs/zh/standards/SRGF.md
> +        },
UIGF 和 UIAF 传下来的习惯吧，各种字段都用字串符

2023-05-22 02:39 UTC, Masterain98 commented on docs/zh/standards/SRGF.md
> +        },
更新为数字了