⚡  重制相关项目组件 ⭐
UIGF-org/UIGF-org.github.io pull request #38
Opened 2023-10-29 13:47 UTC by Kamisato-Ayaka-233

2023-10-30 07:29 UTC, Masterain98 requested changes
1. 亮色主题下的遮罩效果是暗色主题的
![image](https://github.com/UIGF-org/UIGF-org.github.io/assets/10614984/cae8b865-0989-418d-92ca-c9cab7a55a4c)
2. 使用相对路径的preview图片没有正确加载
![image](https://github.com/UIGF-org/UIGF-org.github.io/assets/10614984/e5f81ad1-4398-41db-b7a3-bb3fbd294417)
3. 右下角的 GitHub 图标按钮，指针悬浮时会出现一个类似悬浮超链接的下划线 （未测试其它图标）
![image](https://github.com/UIGF-org/UIGF-org.github.io/assets/10614984/4bd6a4f6-d487-44a2-999a-f02dd9025b17)
4. 点击box时，如果位置正好是中间的logo，浏览器不仅会在新tab中打开页面，还会在当前页面打开图片
![image](https://github.com/UIGF-org/UIGF-org.github.io/assets/10614984/ff2a86b0-ed00-400f-8439-9d2a8b3c0720)

2023-10-30 08:50 UTC, Lightczx commented
> 4\. 点击box时，如果位置正好是中间的logo，浏览器不仅会在新tab中打开页面，还会在当前页面打开图片

Epic!!!

2023-10-30 10:50 UTC, Kamisato-Ayaka-233 commented
> 点击box时，如果位置正好是中间的logo，浏览器不仅会在新tab中打开页面，还会在当前页面打开图片

az，我也不知道怎么回事呀，可能是这个项目有加什么插件吧？
只要点击到`img`元素，就会进入大图模式，也不知道如何取消呀！

2023-11-01 22:50 UTC, Masterain98 requested changes
@Kamisato-Ayaka-233 在自动识别主题时，判定亮色情况下，遮罩效果仍然是暗色的。但手动切换到亮色主题时是没问题的。

2023-11-02 12:36 UTC, Kamisato-Ayaka-233 commented
> @Kamisato-Ayaka-233 在自动识别主题时，判定亮色情况下，遮罩效果仍然是暗色的。但手动切换到亮色主题时是没问题的。
> 
> ![image](https://github.com/UIGF-org/UIGF-org.github.io/assets/10614984/66989d96-7ed4-4b26-a526-dca3c65d77a7)
> 

（或许应该试着把`prefers-color-scheme`添加事件监听器的函数调到外面？）

2023-11-03 07:53 UTC, Masterain98 requested changes
第一次访问页面时，自动主题下遮罩效果是正确的，但在右上角点击一轮再回到自动时，遮罩效果是错误的

2023-11-03 12:58 UTC, merged