Introducing UIGF v3.0
UIGF-org/UIGF-org.github.io pull request #52
Opened 2024-03-01 13:29 UTC by Lightczx

gacha_type 新增枚举值 500 (并非一个确定性的值，目前仅用于占位表述新的卡池类型，在游戏更新后，才能最终确定实际使用的值)

2024-03-01 13:33 UTC, BTMuli approved these changes

2024-03-01 13:34 UTC, MUKAPP approved these changes

2024-03-01 13:34 UTC, sunfkny approved these changes

2024-03-01 13:35 UTC, bakaomg approved these changes

2024-03-01 13:40 UTC, MoRanYue approved these changes

2024-03-01 13:47 UTC, Scighost approved these changes

2024-03-01 13:57 UTC, lulu666lulu approved these changes

2024-03-01 13:57 UTC, Womsxd approved these changes

2024-03-01 14:04 UTC, qhy040404 approved these changes

2024-03-01 14:06 UTC, MiniGrayGay approved these changes

2024-03-01 14:19 UTC, LaoshuBaby approved these changes

2024-03-01 14:39 UTC, huiyadanli approved these changes

2024-03-01 15:12 UTC, TremblingMoeNew approved these changes

2024-03-01 15:48 UTC, cntvc approved these changes

2024-03-01 18:50 UTC, Masterain98 commented
- [ ] 需要更新 [schema](https://github.com/UIGF-org/UIGF-org.github.io/blob/main/docs/.vuepress/public/schema/uigf.json)
- [ ] 2.4版本的文档需要归档一份

2024-03-01 18:50 UTC, Masterain98 requested changes
- [ ] 2.4版本的文档需要归档一份

2024-03-02 12:07 UTC, biuuu approved these changes

2024-03-03 03:10 UTC, Lightczx commented
> * [ ]  2.4版本的文档需要归档一份

你能改下么，顺便把英文版的也翻译了（

2024-03-03 06:28 UTC, Masterain98 approved these changes

2024-03-03 06:37 UTC, BTMuli approved these changes

2024-03-13 03:41 UTC, merged