Update partnership list, adding PizzaHelper4HSR.
UIGF-org/UIGF-org.github.io pull request #65
Opened 2024-05-02 07:50 UTC by ShikiSuen

两个改变：
1. 新增穹披助手（SRGF v1）。
2. 以中文的合作伙伴清单为依据，重做了英文的合作伙伴清单。

这个 PR 先缓半天到一天再合并，得给 @Bill-Haku 一些时间将素材上传到披萨助手系列的网站上。

![2tCMLniNxM](https://github.com/UIGF-org/UIGF-org.github.io/assets/3164826/e8ed0e50-b458-477d-9914-4ea18e4a3348)

2024-05-02 08:01 UTC, Bill-Haku requested changes

2024-05-02 08:01 UTC, Bill-Haku commented on docs/en/partnership-list.md
> +preview="https://gi.pizzastudio.org/img/hsrhelper-srgf-preview.png"
```suggestion
preview="https://hsr.pizzastudio.org/img/hsrhelper-srgf-preview.png"
```

2024-05-02 08:01 UTC, Bill-Haku commented on docs/zh/partnership-list.md
> +logo="https://gi.pizzastudio.org/img/hsrhelper_logo_clipped.png"
```suggestion
logo="https://hsr.pizzastudio.org/img/icon.hsrhelper.clipped.png"
```

2024-05-02 08:01 UTC, Bill-Haku commented on docs/zh/partnership-list.md
> +preview="https://gi.pizzastudio.org/img/hsrhelper-srgf-preview.png"
```suggestion
preview="https://hsr.pizzastudio.org/img/hsrhelper-srgf-preview.png"
```

2024-05-02 08:06 UTC, Bill-Haku approved these changes

2024-05-02 08:15 UTC, ShikiSuen commented
@Masterain98 披萨助手的条目修改已经全部搞定了，可以正式进入你们的 review 环节。
有要修改的地方可以直接修改，弄完之后你们觉得没问题的话就直接 merge 吧。

2024-05-02 08:18 UTC, BTMuli commented on docs/en/partnership-list.md
> +name="提瓦特小助手 (YSHelper)"
YSHelper

2024-05-02 08:21 UTC, BTMuli requested changes

2024-05-02 08:21 UTC, BTMuli commented on docs/en/partnership-list.md
> +desc="米家游戏启动器"
Game Launcher for miHoYo

2024-05-02 08:21 UTC, BTMuli commented on docs/en/partnership-list.md
> +desc="米家游戏启动器"
下面那些描述已经是en的同样需要改回去

2024-05-02 08:21 UTC, BTMuli commented on docs/en/partnership-list.md
> +version="不支持 UIGF 导出"
这里version改成英文，尽可能简短

2024-05-02 16:41 UTC, ShikiSuen commented
这个没问题的话就合并了吧。

2024-05-02 16:56 UTC, merged

2024-05-03 08:57 UTC, Masterain98 commented
已经重新部署了，合并时部署抽风构建失败了。