Introducing UIGF v4.0
UIGF-org/UIGF-org.github.io pull request #70
Opened 2024-07-10 06:37 UTC by Lightczx

2024-07-10 06:38 UTC, AuroraZiling approved these changes

2024-07-10 08:07 UTC, BTMuli requested changes

2024-07-10 08:26 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +1. 必须在同时支持 UIGF 数据格式**导入**和**导出**功能
那么请问「并在相关功能区域或文档中提供跳转至 [UIGF-Org](https://uigf.org) 的超链接后声明支持 UIGF 格式」从现在开始不需要了吗？

2024-07-10 09:11 UTC, ShikiSuen commented
这种 type 二义性对部分 type-safe 语言非常不友好。
如果 UIGFv4 还有商讨的余地的话，建议将所有用到 stringed integers 的栏位都强制要求 string。
integer 的话可能会被某些刻意制造的 json 攻击（手段是写入数值过大的 integer value）。

cc @Scighost 
<img width="316" alt="image" src="https://github.com/UIGF-org/UIGF-org.github.io/assets/3164826/8d24e72f-293d-4466-8071-d52cd5f78589">

2024-07-10 09:13 UTC, bakaomg approved these changes

2024-07-10 09:24 UTC, ShikiSuen requested changes

2024-07-10 09:24 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +                    "type": "string|integer",
```suggestion
                    "type": "string",
```
I suggest using String in this field due to concerns I have said above.

Also, the timestamp in Swift is Double.
https://developer.apple.com/documentation/uikit/uievent/1613790-timestamp

2024-07-10 09:24 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +                        "type": "string|integer",
```suggestion
                        "type": "string",
```
I suggest using String in this field due to concerns I have said above.

2024-07-10 09:24 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +                        "type": "string|integer",
```suggestion
                        "type": "string",
```
I suggest using String in this field due to concerns I have said above.

2024-07-10 09:24 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +                        "type": "string|integer",
```suggestion
                        "type": "string",
```
I suggest using String in this field due to concerns I have said above.

2024-07-10 11:55 UTC, qhy040404 commented on docs/zh/standards/uigf.md
> +                                        "5"
API raw values are in ONE digit.

2024-07-10 14:01 UTC, TremblingMoeNew requested changes
由于本次为不具备向前兼容性的中断性更新，事实上与旧版UIGF相当于是两种不一样的标准，建议版本号进一步增大，改为UIGF v5.0

---

https://github.com/UIGF-org/UIGF-org.github.io/blob/3adcf576784545799957b6d4b4e999e6990230c8/docs/.vuepress/sidebar/zh.ts#L19-L31

边栏需重新分类；UIGF v4.0应单独分为一类；由于中断性更新问题，UIGF v3.0和SRGF v1.0应当继续保留在边栏中

---

建议添加专门的UIGF v4.0更新说明日志文档，提醒与协助开发者进行新旧版本的兼容

2024-07-10 14:24 UTC, ShikiSuen commented
@TremblingMoeNew 不然改称 HIGF（Hoyoverse Interchangeable GachaLog Format）？

2024-07-11 01:28 UTC, Lightczx commented
> 边栏需重新分类；UIGF v4.0应单独分为一类；由于中断性更新问题，UIGF v3.0和SRGF v1.0应当继续保留在边栏中
> 
> 建议添加专门的UIGF v4.0更新说明日志文档，提醒与协助开发者进行新旧版本的兼容

@Masterain98 cc

2024-07-11 01:39 UTC, ShikiSuen approved these changes

2024-07-11 02:10 UTC, Masterain98 commented
![image](https://github.com/UIGF-org/UIGF-org.github.io/assets/10614984/d95357ca-e0a7-4eab-a57f-7e2e7b06a591)
@UIGF-org/uigf-update-audience @Lightczx @TremblingMoeNew Looks good?

2024-07-11 02:11 UTC, Lightczx commented
LGTM

2024-07-11 03:51 UTC, BTMuli requested changes

2024-07-11 03:51 UTC, BTMuli commented on docs/zh/standards/uigf-legacy-v2.2.md
> +该标准已过时，[UIGF v2.4](uigf.md) 替代了本标准。本页面已归档，请使用最新的 [UIGF 标准](./uigf.md)。
这里两句话合并一下是不是更好一点？

2024-07-11 03:51 UTC, BTMuli commented on docs/zh/standards/uigf-legacy-v3.0.md
> +仅包含导入或导出功能降低了用户数据可流通性，且将数据置于用户不可控的风险中，不符合 UIGF-Org 设计的初衷。
建议加粗

2024-07-11 03:51 UTC, BTMuli commented on docs/zh/standards/uigf-legacy-v3.0.md
> +应用必须在同时支持 UIGF 数据格式**导入**和**导出**功能并在相关功能区域或文档中提供跳转至 [UIGF-Org](https://uigf.org) 的超链接后声明支持 UIGF 格式
还是拆开吧，一句话读着有点累T_T

2024-07-11 07:24 UTC, Masterain98 commented
https://github.com/UIGF-org/UIGF-org.github.io/blob/c5db1b0530584f1db47c0b7c6681130404d23c98/docs/zh/standards/uigf.md?plain=1#L153-L163

关于 Json Schema 的问题：
1. `API 返回` 是否应该强调为`米哈游 API 返回 `
2. `time` 的解释是否应该强调为服务器时间？可能会产生歧义，并且可能与`API 返回`相悖

2024-07-11 09:44 UTC, Bill-Haku approved these changes

2024-07-11 09:49 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +                                    "description": "抽取物品时对应时区（timezone）下的本地时间"
这个栏位最好是保留从米哈游伺服器获取的原始时间字串，因为这个时间始终是 UID 所属区服的伺服器时间。
这样的话，哪怕没有 timezone 资讯，也可以根据 UID 倒推出 timezone。
至于「要让用户以当地时间格式来看这个时间」的需求，则应该由 App 自行实作到各自的介面上。

2024-07-11 09:50 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +                                    "description": "抽取物品时对应时区（timezone）下的本地时间"
实在不行的话（比如历史兼容目的），则新增 serverTime 栏位用来保存从 server 获取的 raw time string。

2024-07-11 14:17 UTC, TremblingMoeNew approved these changes

2024-07-11 15:47 UTC, ShikiSuen approved these changes

2024-07-12 00:43 UTC, BTMuli approved these changes

2024-07-12 01:42 UTC, KimigaiiWuyi approved these changes

2024-07-12 01:52 UTC, Masterain98 commented
![image](https://github.com/user-attachments/assets/faaafca8-6d50-49e0-ab96-f9ef1e7c131e)

@UIGF-org/uigf-constitutors  是否应该强调语言代码的格式？（图来源 SRGF v1.0）

2024-07-12 03:11 UTC, qhy040404 approved these changes

2024-07-12 03:13 UTC, Masterain98 approved these changes

2024-07-12 03:28 UTC, ShikiSuen requested changes

2024-07-12 03:28 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +                                    "description": "抽取物品时对应时区（timezone）下的本地时间"
原神没有 region_time_zone，需要从 UID 倒推。

2024-07-12 03:34 UTC, ShikiSuen approved these changes

2024-07-12 04:21 UTC, ShikiSuen approved these changes

2024-07-12 08:16 UTC, ShikiSuen approved these changes

2024-07-12 08:20 UTC, Scighost commented
> `string|integer` 这种 type 二义性对部分 type-safe 语言非常不友好。 （放到 Swift 就是超出三倍的实作成本。） 如果 UIGFv4 还有商讨的余地的话，建议将所有用到 stringed integers 的栏位都强制要求 string。 integer 的话可能会被某些刻意制造的 json 攻击（手段是写入数值过大的 integer value）。
> 
> cc @Scighost <img alt="image" width="316" src="https://private-user-images.githubusercontent.com/3164826/347339128-8d24e72f-293d-4466-8071-d52cd5f78589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzI1MzEsIm5iZiI6MTcyMDc3MjIzMSwicGF0aCI6Ii8zMTY0ODI2LzM0NzMzOTEyOC04ZDI0ZTcyZi0yOTNkLTQ0NjYtODA3MS1kNTJjZDVmNzg1ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDgxNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTMwMjFkZTY4OTIwOGRkZjdlMDFlODJkMWFlNGNkODAyYjBkZTMxODBiN2RhMzgxY2QzMWE5N2IwOThkMzgxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QVeo4Q05Od53Jl_6AGyLix9TQ5rF5NnBBhOBUUee1vk">


可以呀，改成 `string`, `integer`, `string|integer` 我都没意见

2024-07-12 08:21 UTC, Scighost approved these changes

2024-07-12 08:21 UTC, Lightczx commented
> 可以呀，改成 `string`, `integer`, `string|integer` 我都没意见

已经定成 oneof string integer了

2024-07-12 08:45 UTC, ShikiSuen commented
> 已经定成 oneof string integer了

可。实测 QuickType 能够正常解析该 Schema。没有疑虑了。

2024-07-12 22:26 UTC, ShikiSuen approved these changes

2024-07-13 12:45 UTC, ShikiSuen approved these changes

2024-07-13 14:53 UTC, Natrium0521 requested changes

2024-07-13 14:53 UTC, Natrium0521 commented on docs/zh/standards/uigf.md
> +                                "gacha_type",
这里应该加个 `gacha_id` ， `srgf_v1.0` 里是有的，用于区分同时开的同类型卡池

2024-07-13 23:42 UTC, BTMuli commented
本标准起码得等到绝区零下个版本，卡池经过一次迭代后才会合并，在此之前不会有较为巨大的变动。

各位开发者可以着手实现相关功能，但是**务必注明标准还在制定当中或者添加对应tag(beta or dev)**，以免后期可能出现的 breaking change。

@UIGF-org/uigf-update-audience @UIGF-org/uigf-constitutors @UIGF-org/srgf-update-audience @UIGF-org/srgf-constitutors

2024-07-13 23:55 UTC, ShikiSuen commented on docs/zh/standards/uigf.md
> +                                "gacha_type",
刚刚群内开会讨论过后一致认为星穹铁道的这个字段得设为 non-nullable。
于是我刚刚修了，详见 3e8b729。

2024-07-14 03:53 UTC, Natrium0521 approved these changes

2024-07-23 00:49 UTC, earthjasonlin commented
希望能完善`timezone`相关的文档表述，还有`list`里面`time`的；API的这个`region_time_zone`好像国服是`0`，那是什么意思呢；应该转化成什么呢；我看DismissedLight大佬的UIGF导出后不管哪个服`timezone`都是0

2024-07-23 01:12 UTC, Lightczx commented
> 希望能完善`timezone`相关的文档表述，还有`list`里面`time`的；API的这个`region_time_zone`好像国服是`0`，那是什么意思呢；应该转化成什么呢；我看DismissedLight大佬的UIGF导出后不管哪个服`timezone`都是0

API返回: time:LocalTime + region_time_zone: LocalTimeZone
UIGF 4 在选定任一时区后： time: LocalTime + timezone: LocalTimeZone

例如：你在 2024.07.23 10:00:00+08:00 在国服抽取了一个物品
那么在你从服务器获取到记录时由于国服处于东八区：
time: 2024.07.23 10:00:00 region_time_zone: 8
此时如果你选择 UTC+0 作为基准时区，则导出时：
time: 2024.07.23 02:00:00 timezone: 0
选择其他时区均会得出类似结果，导出时允许选择任意时区
同样导入时也必须能够处理任意时区下的记录

2024-07-23 03:19 UTC, earthjasonlin commented
就是导出时要根据region_time_zone来把time转成用户选择的时区吗？
但国服为例，国服的api的region_time_zone为0，基准不就是北京时间吗，这样也没法获取到UTC啊

2024-07-23 04:05 UTC, earthjasonlin commented
> > 希望能完善`timezone`相关的文档表述，还有`list`里面`time`的；API的这个`region_time_zone`好像国服是`0`，那是什么意思呢；应该转化成什么呢；我看DismissedLight大佬的UIGF导出后不管哪个服`timezone`都是0
> 
> API返回: time:LocalTime + region_time_zone: LocalTimeZone UIGF 4 在选定任一时区后： time: LocalTime + timezone: LocalTimeZone
> 
> 例如：你在 2024.07.23 10:00:00+08:00 在国服抽取了一个物品 那么在你从服务器获取到记录时由于国服处于东八区： time: 2024.07.23 10:00:00 region_time_zone: 8 此时如果你选择 UTC+0 作为基准时区，则导出时： time: 2024.07.23 02:00:00 timezone: 0 选择其他时区均会得出类似结果，导出时允许选择任意时区 同样导入时也必须能够处理任意时区下的记录

现在绝区零的API返回的是`"time": "2024-07-19 07:59:38","region_time_zone": 0`，但这个时间是直接显示在抽卡记录页面的，也就是说这个`2024-07-19 07:59:38`就是服务器时间，这样的话绝区零不是无法直接从api获取到时区了吗
原神的api已经没有`region_time_zone`这一项了，但它公示了每个服务器的时区还好说，绝区零也没说每个服务器的时区是什么

2024-07-24 07:34 UTC, merged