71 proj card dev
UIGF-org/UIGF-org.github.io pull request #72
Opened 2024-07-24 13:38 UTC by BTMuli

更改未竟，PR先行）

2024-07-24 18:25 UTC, ShikiSuen commented
那啥：穹披助手对 SRGFv1 的导入导出支持仍在，没必要删掉吧。

（原披助手对 GIGF (也就是 UIGF v2.2 - v3) 只有导入支持、没有导出支持。）

2024-07-25 03:58 UTC, BTMuli commented
@UIGF-org/srgf-update-audience @UIGF-org/srgf-update-audience @UIGF-org/uiaf-update-audience

2024-07-25 08:52 UTC, Masterain98 requested changes
![image](https://github.com/user-attachments/assets/edd57845-c9ce-48b1-a964-c88466cda50b)

我瞎了

2024-07-25 10:59 UTC, ShikiSuen approved these changes

2024-07-26 00:50 UTC, Lightczx approved these changes

2024-07-26 00:50 UTC, merged