添加流萤工具箱的UIGFv4支持
UIGF-org/UIGF-org.github.io pull request #76
Opened 2024-07-26 15:34 UTC by BTMuli

见#73

2024-07-26 15:39 UTC, Natrium0521 requested changes

2024-07-26 15:39 UTC, Natrium0521 commented on docs/zh/partnership-list.md
> +    <Pcb label="UIGF v4.0" :games="['ys_', 'sr', 'zzz_']" bg="purple"></Pcb>
在这加SRGF吧，下面的可以删了

2024-07-26 15:39 UTC, Natrium0521 commented on docs/zh/partnership-list.md
>      desc="《崩坏：星穹铁道》工具集">
这里可以删了，en的同理

2024-07-26 15:57 UTC, Natrium0521 approved these changes

2024-07-28 14:50 UTC, Lightczx commented
@Masterain98 FYI

2024-07-28 14:50 UTC, Lightczx approved these changes

2024-07-30 14:06 UTC, Natrium0521 commented
不merge吗，5个pr了已经（
![aa54e22c348600e285f805521996431e](https://github.com/user-attachments/assets/c33b7d5b-681c-41de-92b6-bbe913bc7456)

2024-07-31 01:00 UTC, merged