添加 Hollow 的 UIGF v4.0 认证
UIGF-org/UIGF-org.github.io pull request #80
Opened 2024-07-27 09:59 UTC by AuroraZiling

导出文件样本：
[Hollow_1722074205.json](https://github.com/user-attachments/files/16398938/Hollow_1722074205.json)

验证通过截图：
![image](https://github.com/user-attachments/assets/447fa781-647c-4f21-be8e-90faadf86d44)

2024-07-27 10:35 UTC, BTMuli requested changes

2024-07-27 10:35 UTC, BTMuli commented on docs/en/partnership-list.md
> +      repo="https://github.com/AuroraZiling/Hollow"
1. 缩进2空格
2. 网站与仓库地址相同的话可以不填
3. 图片用的也是图床，不如存在 `public` 目录，加载的时候起码不会裂开

2024-07-27 11:54 UTC, BTMuli approved these changes

2024-07-28 07:50 UTC, earthjasonlin commented
亚服是UTC+9吗？还是UTC+8

2024-07-28 08:31 UTC, AuroraZiling commented
网上查了是9，但是没有号去测试（）

2024-07-28 14:54 UTC, Lightczx approved these changes

2024-08-12 01:36 UTC, Lightczx commented
请按新的 Badge 规则重新创建新的 PR

2024-08-12 01:36 UTC, closed without merging