添加UIGF与UIAF合作项目-旅者行囊
UIGF-org/UIGF-org.github.io pull request #94
Opened 2024-10-06 07:13 UTC by DreamedWorker

旅者行囊-以原神内容为核心的macOS平台工具集软件

<img width="1219" alt="截屏2024-10-06 15 06 26" src="https://github.com/user-attachments/assets/19c7f9f2-9614-464d-adb6-045f58785a6a">
（图1：UIGF v4.0 JSON骨架校验通过）

<img width="1216" alt="截屏2024-10-06 15 07 54" src="https://github.com/user-attachments/assets/dd6ae6cd-dbd9-47e7-8dd9-c332305f4977">
（图2：UIAF v1.1 JSON骨架校验通过）

2024-10-06 08:54 UTC, Lightczx commented
提交了很多多余.DS_Store文件，需要删除

2024-10-06 15:49 UTC, DreamedWorker commented
> 提交了很多多余.DS_Store文件，需要删除

已经删除了Finder产生的隐藏文件

2024-10-07 01:31 UTC, Lightczx commented
![image](https://github.com/user-attachments/assets/f3abe972-54c5-4053-9454-307d8831bb8d)
你可以看看别的项目的badge都是怎么写的

2024-10-07 02:02 UTC, BTMuli requested changes

2024-10-07 02:02 UTC, BTMuli commented on docs/en/partnership-list.md
> +   icon="/public/projIcon.png"
图片放在 `/public/partnerships` 下另起目录，目录名以项目名称为佳

2024-10-07 02:02 UTC, BTMuli commented on docs/zh/partnership-list.md
> +   repo="https://github.com/DreamedWorker/TravellersBag"
新项目放在已有项目后面，UIAF同上

2024-10-07 05:32 UTC, BTMuli requested changes

2024-10-07 05:32 UTC, BTMuli commented on docs/en/partnership-list.md
> +     <Pcb label="UIAF v1.1" :games="['ys']" bg="yellow"></Pcb>
UIAF与UIGF分开，UIAF在下面部分

2024-10-07 10:48 UTC, BTMuli requested changes

2024-10-07 10:48 UTC, BTMuli commented on docs/en/partnership-list.md
> +     <Pcb label="UIAF v1.1" :games="['ys', 'sr_', 'zzz_']" bg="yellow"></Pcb>
UIGF v4标准是适配原铁绝的，所以才需要展示对于这三者的支持，UIAF仅针对原神，games里面分一个ys就行

2024-10-07 10:52 UTC, DreamedWorker commented on docs/en/partnership-list.md
> +     <Pcb label="UIAF v1.1" :games="['ys', 'sr_', 'zzz_']" bg="yellow"></Pcb>
感谢提醒，我已经修正了我的编写错误

2024-10-07 11:01 UTC, BTMuli commented on docs/en/partnership-list.md
> +     <Pcb label="UIGF v4.0" :games="['ys', 'sr_', 'zzz_']" bg="yellow"></Pcb>
背景色定义于 
https://github.com/UIGF-org/UIGF-org.github.io/blob/main/docs%2F.vuepress%2Fcomponents%2FProjCardBadge.vue#L23-L23 不在其中的默认为主题色

来自个人站点的图片可能会出现加载问题（我这边点击预览就没加载出来），建议用图床或者放到 `public/partnership` 目录下，图片路径引用以 `/partership` 开头， `/public` 应删去

2024-10-07 11:17 UTC, BTMuli requested changes

2024-10-07 11:17 UTC, BTMuli commented on public/partnerships/travellersbag/projBg.png
图片路径位于 `/docs/.vuepress/public/` 下而非根目录的 `public` 目录，~~你就没发现其他项目吗~~

2024-10-07 11:24 UTC, DreamedWorker commented on public/partnerships/travellersbag/projBg.png
重新调整了 （自己前端经验十分匮乏，亦不知道vuepress框架原理，感谢多次耐心提醒

2024-10-07 11:26 UTC, BTMuli approved these changes

2024-10-07 11:26 UTC, BTMuli commented
LGTM, @Lightczx Squash plz.

2024-10-07 11:29 UTC, BTMuli commented
@DreamedWorker 上游更新了，请同步

2024-10-14 00:40 UTC, Masterain98 approved these changes

2024-10-14 00:47 UTC, BTMuli commented
@DreamedWorker 上游更新了，请同步

2024-10-14 01:17 UTC, Lightczx commented
https://github.com/DreamedWorker/UIGF-org.github.io/blob/0a4290e0402e87fad5d6bc454393ac0b153bb985/docs/en/partnership-list.md?plain=1#L192-L220
你有检查你合并后的内容么

2024-10-14 01:36 UTC, merged