Update information regarding The Pizza Helper.
UIGF-org/UIGF-org.github.io pull request #98
Opened 2024-12-03 18:46 UTC by ShikiSuen

原神披萨小助手跟星穹铁道披萨小助手都被淘汰了，于是删除相关记录、新增基于统一披萨引擎的「披萨小助手」。

2024-12-03 22:52 UTC, BTMuli requested changes

2024-12-03 22:52 UTC, BTMuli commented on docs/en/partnership-list.md
> +  <Pcd
新项目统一置后

2024-12-03 22:52 UTC, BTMuli commented on docs/en/partnership-list.md
> +    icon="https://raw.githubusercontent.com/pizza-studio/PizzaHelperUnited/refs/heads/main/PromotionMaterials/UIGF/ThePizzaHelper-logo-clipped.png"
背景跟图标存partnership下单独目录

2024-12-04 02:14 UTC, ShikiSuen commented on docs/en/partnership-list.md
> +  <Pcd
> 新项目统一置后

商店网址没变，于是还是用之前原神披萨小助手的顺序位置吧。

2024-12-04 02:18 UTC, Lightczx requested changes
需要移动至列表末尾

2024-12-04 02:19 UTC, Lightczx approved these changes

2024-12-04 02:25 UTC, merged